### ISSUE TITLE
Quick Question About Your Flask Website Deployment on AWS

### ISSUE THREAD

**Issue by yy2460** [prasad217/NLP-Based-Text-Summarizer-Web-Application#1]
Hey, hi!

I noticed you deployed your Flask website on AWS, and it looks awesome. I'm working on something similar and was wondering if you could share how you went about the deployment process.

Specifically, I'm curious about:

- The steps you took to set up the AWS environment.
- How you configured the Flask app for deployment.
- Any challenges you faced and how you handled them.

Your insights would be super helpful! If you have any docs or tips, I'd really appreciate it.

Thanks a lot!

**Comment by prasad217** [comment]
hey shankar,

Sure thing! I’ve actually documented the entire deployment process on my website. I included all the details on how I deployed my NLP-based text summarization project. You can check it out [here](https://deployment-guide.vercel.app/).

Just a heads up on a couple of challenges I faced:

Torch Installation: Installing Torch on the EC2 instance was a bit of a pain because it's quite large. It took some time, so be prepared for that.
Nginx Configuration: Everything else was pretty smooth, but make sure you configure Nginx correctly. It’s not too tricky, but it’s worth double-checking.
Also, if you’re planning to deploy on the free tier, be sure to check out all the warnings I’ve included on the site. I added images for better understanding, so it should be pretty straightforward.

Let me know if you run into any issues or need more help!
